version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_db
    ports:
      - "5432:5432" # Map host port to container port